apiVersion: v1
kind: ConfigMap
metadata:
  name: resource-policy
  namespace: trustee-operator-system
data:
  policy.rego: |
    package policy
    import rego.v1
  {{- if eq .Values.global.coco.secured true }}
    default allow = true
  {{- else }}
    default allow = false
  {{- end  }}
    allow if {
        input["submods"]["cpu0"]["ear.status"] == "affirming"
    }