{{ if .Values.global.coco.secured }}
---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: rvps-policy
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: rvps-policy-cp
      spec:
        remediationAction: enforce
        severity: medium
        object-templates:

        - complianceType: mustonlyhave
          objectDefinition:
            apiVersion: v1
            kind: ConfigMap
            metadata:
              name: rvps-reference-values
              namespace: trustee-operator-system
            data:
              reference-values.json: |
                [
                  {
                    "name": "snp_pcr03",
                    "expiration": "2027-12-12T00:00:00Z",
                    "value": [
                      "{{ `{{ (fromJson (fromSecret 'trustee-operator-system' 'pcr_stash' 'json' | toLiteral)).measurments.sha256.pcr03 }}` }}"
                    ]
                  },
                  {
                    "name": "tdx_pcr03",
                    "expiration": "2027-12-12T00:00:00Z",
                    "value": [
                      "{{ `{{ (fromJson (fromSecret 'trustee-operator-system' 'pcr_stash' 'json' | toLiteral)).measurments.sha256.pcr03 }}` }}"
                    ]
                  },
                  {
                    "name": "snp_pcr08",
                    "expiration": "2027-12-12T00:00:00Z",
                    "value": [
                      "{{ `{{ fromConfigMap 'imperative' 'initdata' 'PCR8_HASH' }}` }}"
                    ]
                  },
                  {
                    "name": "tdx_pcr08",
                    "expiration": "2027-12-12T00:00:00Z",
                    "value": [
                      "{{ `{{ fromConfigMap 'imperative' 'initdata' 'PCR8_HASH' }}` }}"
                    ]
                  },
                  {
                    "name": "snp_pcr09",
                    "expiration": "2027-12-12T00:00:00Z",
                    "value": [
                      "{{ `{{ (fromJson (fromSecret 'trustee-operator-system' 'pcr_stash' 'json' | toLiteral)).measurments.sha256.pcr09 }}` }}"
                    ]
                  },
                  {
                    "name": "tdx_pcr09",
                    "expiration": "2027-12-12T00:00:00Z",
                    "value": [
                      "{{ `{{ (fromJson (fromSecret 'trustee-operator-system' 'pcr_stash' 'json' | toLiteral)).measurments.sha256.pcr09 }}` }}"
                    ]
                  },
                  {
                    "name": "snp_pcr11",
                    "expiration": "2027-12-12T00:00:00Z",
                    "value": [
                      "{{ `{{ (fromJson (fromSecret 'trustee-operator-system' 'pcr_stash' 'json' | toLiteral)).measurments.sha256.pcr11 }}` }}"
                    ]
                  },
                  {
                    "name": "tdx_pcr11",
                    "expiration": "2027-12-12T00:00:00Z",
                    "value": [
                      "{{ `{{ (fromJson (fromSecret 'trustee-operator-system' 'pcr_stash' 'json' | toLiteral)).measurments.sha256.pcr11 }}` }}"
                    ]
                  },
                  {
                    "name": "snp_pcr12",
                    "expiration": "2027-12-12T00:00:00Z",
                    "value": [
                      "{{ `{{ (fromJson (fromSecret 'trustee-operator-system' 'pcr_stash' 'json' | toLiteral)).measurments.sha256.pcr12 }}` }}"
                    ]
                  },
                  {
                    "name": "tdx_pcr12",
                    "expiration": "2027-12-12T00:00:00Z",
                    "value": [
                      "{{ `{{ (fromJson (fromSecret 'trustee-operator-system' 'pcr_stash' 'json' | toLiteral)).measurments.sha256.pcr12 }}` }}"
                    ]
                  }
                ]
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: rvps-placement-binding
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
placementRef:
  name: rvps-placement-rule
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: rvps-policy
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: rvps-placement-rule
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchLabels:
      local-cluster: "true"
---
{{ end }}
